export function getSetupCopy(lang: string) {
  if (lang === "es") {
    return {
      channelsEmpty: "WhatsApp se configura con Novua durante el onboarding.",
      channelUsage: "Se usa para recibir y responder mensajes entrantes.",
      channelsNote: "Configurado por Novua durante onboarding.",
      requestSetup: "Solicitar setup",
      requestWhatsAppSetup: "Solicitar setup de WhatsApp",
      requestInstagramSetup: "Solicitar setup de Instagram",
      updateWhatsAppSetup: "Actualizar solicitud",
      updateInstagramSetup: "Actualizar solicitud de Instagram",
      setupRequested: "Setup solicitado",
      setupInProgress: "Setup en curso",
      setupRequestedNote: "Estamos preparando contigo la conexión real de WhatsApp.",
      setupInstagramRequestedNote: "Estamos preparando contigo la conexión real de Instagram con tu Meta Business.",
      setupPhoneRequired: "Es obligatorio indicar el número de WhatsApp.",
      setupInstagramRequired: "Es obligatorio indicar el usuario de Instagram.",
      setupNumberLabel: "Número de WhatsApp",
      setupNumberPlaceholder: "+34 600 111 222",
      setupInstagramHandleLabel: "Usuario de Instagram",
      setupInstagramHandlePlaceholder: "@clinica",
      instagramHandle: "Usuario conectado",
      instagramChannelHelp:
        "Conecta la cuenta de Instagram Business del cliente con su Meta. Novua activa el canal cuando la autorización esté lista.",
      setupMetaVerifiedLabel: "¿Tienes Meta Business verificado?",
      setupMetaVerifiedYes: "Sí",
      setupMetaVerifiedNo: "No",
      setupNotesLabel: "Nota",
      setupNotesPlaceholder: "Nombre de contacto, disponibilidad o cualquier detalle útil.",
      inviteTitle: "Añade agentes o admins al mismo workspace.",
      inviteEmail: "Email",
      inviteRole: "Rol",
      inviteUser: "Invitar usuario",
      invitePending: "Enviando invitación...",
      inviteSuccess: "Invitación enviada.",
      inviteAdmin: "Admin",
      inviteAgent: "Agente",
      inviteOwner: "Propietario",
      inviteError: "No se pudo enviar la invitación.",
      seatLimitError: "Límite de usuarios alcanzado para este plan.",
      pendingInvites: "Invitaciones pendientes",
      resendInvite: "Reenviar",
      cancelInvite: "Cancelar",
      resendPending: "Reenviando...",
      cancelPending: "Cancelando...",
      inviteResent: "Invitación reenviada.",
      inviteCancelled: "Invitación cancelada.",
      removeUser: "Eliminar acceso",
      removingUser: "Eliminando...",
      removeUserSuccess: "Acceso eliminado.",
      removeUserError: "No se pudo eliminar el acceso.",
      reassignPlaceholder: "Reasignar a...",
      reassignAction: "Reasignar",
      reassigningAction: "Reasignando...",
      reassignSuccess: "Conversaciones abiertas reasignadas.",
      reassignError: "No se pudieron reasignar las conversaciones.",
      businessSetupTitle: "Cómo se calcula el valor",
      businessSetupHelp:
        "Define cuánto vale cada tipo de conversación. Esto determina qué aparece primero en el inbox.",
      businessSetupName: "Nombre del negocio",
      businessSetupLeadTypesBlock: "Tipos de consulta y valor estimado (€)",
      businessSetupLeadTypes: "¿Qué tipo de consultas recibes?",
      businessSetupAddLeadType: "+ Añadir tipo",
      businessSetupLeadTypeName: "Nombre",
      businessSetupEstimatedValue: "Valor estimado (€)",
      businessSetupRemoveLeadType: "Eliminar",
      businessSetupSave: "Guardar configuración",
      businessSetupSaving: "Guardando...",
      businessSetupBackfill: "Recalcular conversaciones",
      businessSetupBackfilling: "Recalculando...",
      businessSetupBackfillSuccess: "Conversaciones actualizadas",
      businessSetupReseedDemo: "Recrear demo",
      businessSetupReseedingDemo: "Recreando demo...",
      businessSetupReseedDemoSuccess: "Demo recreada.",
      businessSetupReseedDemoConfirm:
        "Esto borrará los leads demo actuales de esta cuenta y volverá a crear la demo base. ¿Continuar?",
      businessSetupSuccess: "Configuración guardada.",
      businessSetupError: "No se pudo guardar la configuración.",
      pilotFeedbackTitle: "Reportar problema",
      pilotFeedbackHelp: "",
      pilotFeedbackCategory: "Tipo",
      pilotFeedbackMessage: "Cuéntanos qué ha pasado o qué mejorarías.",
      pilotFeedbackSubmit: "Enviar feedback",
      pilotFeedbackSubmitting: "Enviando...",
      pilotFeedbackSuccess: "Feedback enviado.",
      pilotFeedbackError: "No se pudo enviar el feedback.",
      pilotFeedbackBug: "Error",
      pilotFeedbackGeneral: "Comentarios",
      pilotFeedbackFeature: "Solicitud de mejora",
      pilotFeedbackHistoryTitle: "Tus reportes",
      pilotFeedbackHistoryEmpty: "Todavía no has enviado reportes.",
      pilotFeedbackHistoryStatus: "Estado",
      pilotFeedbackHistoryPage: "Página",
      pilotFeedbackHistoryReply: "Respuesta de Novua",
      pilotFeedbackStatusNew: "Nuevo",
      pilotFeedbackStatusReviewed: "Revisado",
      pilotFeedbackStatusClosed: "Cerrado",
      accountTitle: "Tu acceso",
      accountHelp: "Información de la cuenta con la que estás trabajando ahora mismo.",
      accountRole: "Rol",
      accountWorkspace: "Workspace",
      accountEmail: "Email",
      accountPermissions: "Permisos",
      accountPermissionsAgent: "Puedes gestionar conversaciones, responder mensajes y reportar incidencias.",
      accountPermissionsAdmin: "Puedes configurar el workspace, gestionar equipo y operar conversaciones.",
      systemAiAssistance: "Asistencia IA",
      systemFollowUpAutomation: "Automatización de seguimiento",
      systemWhatsappWebhook: "Webhook de WhatsApp",
      noTeamMembers: "No hay miembros del equipo todavía.",
      settingsUnavailable: "Configuración requiere un workspace autenticado y configurado.",
      workspaceModeTitle: "Modo del workspace",
      workspaceModeInternal: "Workspace interno de demo. Aquí se muestran herramientas internas.",
      workspaceModeCustomerDemo:
        "Workspace demo de cliente. Aquí se muestra setup orientado a cliente sin herramientas internas.",
      workspaceModeCustomer: "Workspace cliente. Aquí están activos setup y feedback orientados a cliente.",
      requestError: "No se pudo solicitar el setup ahora mismo.",
      embeddedConnectTitle: "Conectar con Meta",
      embeddedConnectHelp:
        "Haz login con Meta y autoriza tu número una sola vez. Si ya estaba conectado, úsalo solo si dejó de recibir mensajes.",
      embeddedConnectAction: "Conectar con Meta",
      embeddedReconnectAction: "Reconectar canal",
      embeddedSdkLoading: "Cargando conexión...",
      embeddedSdkPreparing: "Preparando Meta...",
      embeddedConnectSuccess: "WhatsApp conectado desde Meta.",
      embeddedConnectError: "No se pudo abrir la conexión con Meta.",
      embeddedSaveError: "Meta terminó el flujo, pero Novua no pudo guardar la conexión.",
      embeddedFallbackTitle: "Si Meta no te deja terminar",
      embeddedFallbackHelp: "Vuelve a intentarlo desde este botón. Si Meta sigue bloqueando el flujo, contacta con Novua.",
      whatsappHowTitle: "Cómo funciona",
      whatsappHowConnected:
        "Este número ya recibe mensajes en Novua. Cada WhatsApp entrante crea o actualiza una conversación en Inbox.",
      whatsappHowDisconnected:
        "Conecta el número desde Meta para que los mensajes entren automáticamente en Inbox.",
      whatsappNumber: "Número conectado",
      whatsappPhoneId: "ID técnico",
      whatsappFlowInbound: "1. El cliente escribe al WhatsApp conectado.",
      whatsappFlowInbox: "2. Novua crea la conversación y la prioriza por valor.",
      whatsappFlowReply: "3. El equipo responde desde Inbox y el cliente lo recibe en su móvil.",
      whatsappNextConnected: "Siguiente paso: envía un mensaje de prueba desde otro móvil y responde desde Inbox.",
      whatsappNextDisconnected: "Siguiente paso: pulsa Conectar con Meta y autoriza el número del cliente.",
      dangerTitle: "Zona peligrosa",
      dangerHelp: "Elimina el workspace, el canal configurado y todos los datos asociados.",
      dangerWarning:
        "Esta acción es irreversible. Se eliminarán contactos, conversaciones, mensajes y accesos del equipo.",
      dangerConfirmationLabel: "Escribe el nombre del workspace para confirmar",
      dangerDeleteLabel: "Eliminar workspace y datos",
      dangerDeletingLabel: "Eliminando...",
      dangerDeletedLabel: "Eliminando workspace. Redirigiendo...",
      dangerError: "No se pudo eliminar el workspace.",
    };
  }

  if (lang === "pt") {
    return {
      channelsEmpty: "O WhatsApp é configurado com a Novua durante o onboarding.",
      channelUsage: "É usado para receber e responder a mensagens de entrada.",
      channelsNote: "Configurado pela Novua durante o onboarding.",
      requestSetup: "Solicitar setup",
      requestWhatsAppSetup: "Solicitar setup de WhatsApp",
      requestInstagramSetup: "Solicitar setup de Instagram",
      updateWhatsAppSetup: "Atualizar solicitação",
      updateInstagramSetup: "Atualizar solicitação de Instagram",
      setupRequested: "Setup solicitado",
      setupInProgress: "Setup em curso",
      setupRequestedNote: "Estamos preparando com você a conexão real do WhatsApp.",
      setupInstagramRequestedNote: "Estamos preparando com você a conexão real do Instagram com a tua Meta Business.",
      setupPhoneRequired: "O número de WhatsApp é obrigatório.",
      setupInstagramRequired: "O utilizador de Instagram é obrigatório.",
      setupNumberLabel: "Número de WhatsApp",
      setupNumberPlaceholder: "+351 912 345 678",
      setupInstagramHandleLabel: "Utilizador de Instagram",
      setupInstagramHandlePlaceholder: "@clinica",
      instagramHandle: "Utilizador conectado",
      instagramChannelHelp:
        "Liga a conta Instagram Business do cliente à Meta dele. A Novua ativa o canal quando a autorização estiver pronta.",
      setupMetaVerifiedLabel: "Tem Meta Business verificado?",
      setupMetaVerifiedYes: "Sim",
      setupMetaVerifiedNo: "Não",
      setupNotesLabel: "Nota",
      setupNotesPlaceholder: "Nome do contato, disponibilidade ou qualquer detalhe útil.",
      inviteTitle: "Adicione agentes ou admins ao mesmo workspace.",
      inviteEmail: "Email",
      inviteRole: "Função",
      inviteUser: "Convidar usuário",
      invitePending: "Enviando convite...",
      inviteSuccess: "Convite enviado.",
      inviteAdmin: "Admin",
      inviteAgent: "Agente",
      inviteOwner: "Proprietário",
      inviteError: "Não foi possível enviar o convite.",
      seatLimitError: "O limite de usuários deste plano foi atingido.",
      pendingInvites: "Convites pendentes",
      resendInvite: "Reenviar",
      cancelInvite: "Cancelar",
      resendPending: "Reenviando...",
      cancelPending: "Cancelando...",
      inviteResent: "Convite reenviado.",
      inviteCancelled: "Convite cancelado.",
      removeUser: "Remover acesso",
      removingUser: "Removendo...",
      removeUserSuccess: "Acesso removido.",
      removeUserError: "Não foi possível remover o acesso.",
      reassignPlaceholder: "Reatribuir para...",
      reassignAction: "Reatribuir",
      reassigningAction: "A reatribuir...",
      reassignSuccess: "Conversas abertas reatribuídas.",
      reassignError: "Não foi possível reatribuir as conversas.",
      businessSetupTitle: "Como calculamos o valor",
      businessSetupHelp:
        "Defina quanto vale cada tipo de conversa. Isso determina o que aparece primeiro no inbox.",
      businessSetupName: "Nome do negócio",
      businessSetupLeadTypesBlock: "Tipos de consulta e valor estimado (€)",
      businessSetupLeadTypes: "Que tipo de consultas recebes?",
      businessSetupAddLeadType: "+ Adicionar tipo",
      businessSetupLeadTypeName: "Nome",
      businessSetupEstimatedValue: "Valor estimado (€)",
      businessSetupRemoveLeadType: "Remover",
      businessSetupSave: "Guardar configuração",
      businessSetupSaving: "Guardando...",
      businessSetupBackfill: "Recalcular conversas",
      businessSetupBackfilling: "Recalculando...",
      businessSetupBackfillSuccess: "Conversas atualizadas",
      businessSetupReseedDemo: "Recriar demo",
      businessSetupReseedingDemo: "Recriando demo...",
      businessSetupReseedDemoSuccess: "Demo recriada.",
      businessSetupReseedDemoConfirm:
        "Isto irá apagar os leads demo atuais desta conta e recriar a demo base. Continuar?",
      businessSetupSuccess: "Configuração guardada.",
      businessSetupError: "Não foi possível guardar a configuração.",
      pilotFeedbackTitle: "Reportar problema",
      pilotFeedbackHelp: "",
      pilotFeedbackCategory: "Tipo",
      pilotFeedbackMessage: "Conta-nos o que aconteceu ou o que melhorarias.",
      pilotFeedbackSubmit: "Enviar feedback",
      pilotFeedbackSubmitting: "Enviando...",
      pilotFeedbackSuccess: "Feedback enviado.",
      pilotFeedbackError: "Não foi possível enviar o feedback.",
      pilotFeedbackBug: "Bug",
      pilotFeedbackGeneral: "Feedback",
      pilotFeedbackFeature: "Pedido de melhoria",
      pilotFeedbackHistoryTitle: "Seus reportes",
      pilotFeedbackHistoryEmpty: "Ainda não enviaste reportes.",
      pilotFeedbackHistoryStatus: "Estado",
      pilotFeedbackHistoryPage: "Página",
      pilotFeedbackHistoryReply: "Resposta da Novua",
      pilotFeedbackStatusNew: "Novo",
      pilotFeedbackStatusReviewed: "Revisado",
      pilotFeedbackStatusClosed: "Fechado",
      accountTitle: "Seu acesso",
      accountHelp: "Informação da conta com a qual você está trabalhando agora.",
      accountRole: "Função",
      accountWorkspace: "Workspace",
      accountEmail: "Email",
      accountPermissions: "Permissões",
      accountPermissionsAgent: "Pode gerir conversas, responder mensagens e reportar incidentes.",
      accountPermissionsAdmin: "Pode configurar o workspace, gerir equipa e operar conversas.",
      systemAiAssistance: "Assistência IA",
      systemFollowUpAutomation: "Automatização de seguimento",
      systemWhatsappWebhook: "Webhook do WhatsApp",
      noTeamMembers: "Ainda não há membros na equipa.",
      settingsUnavailable: "Configurações requerem um workspace autenticado e configurado.",
      workspaceModeTitle: "Modo do workspace",
      workspaceModeInternal: "Workspace interno de demo. Ferramentas internas visíveis.",
      workspaceModeCustomerDemo:
        "Workspace demo de cliente. Setup orientado a cliente sem ferramentas internas.",
      workspaceModeCustomer: "Workspace cliente. Setup e feedback orientados a cliente.",
      requestError: "Não foi possível solicitar o setup.",
      embeddedConnectTitle: "Conectar com Meta",
      embeddedConnectHelp:
        "Faça login com a Meta e autorize o seu número uma única vez. Se já estava ligado, use apenas se deixou de receber mensagens.",
      embeddedConnectAction: "Conectar com Meta",
      embeddedReconnectAction: "Reconectar canal",
      embeddedSdkLoading: "Carregando conexão...",
      embeddedSdkPreparing: "Preparando Meta...",
      embeddedConnectSuccess: "WhatsApp conectado pela Meta.",
      embeddedConnectError: "Não foi possível abrir a conexão com a Meta.",
      embeddedSaveError: "A Meta terminou o fluxo, mas a Novua não conseguiu guardar a conexão.",
      embeddedFallbackTitle: "Se a Meta não deixar terminar",
      embeddedFallbackHelp: "Tente novamente neste botão. Se a Meta continuar bloqueando o fluxo, contate a Novua.",
      whatsappHowTitle: "Como funciona",
      whatsappHowConnected:
        "Este número já recebe mensagens na Novua. Cada WhatsApp recebido cria ou atualiza uma conversa no Inbox.",
      whatsappHowDisconnected:
        "Conecte o número pela Meta para que as mensagens entrem automaticamente no Inbox.",
      whatsappNumber: "Número conectado",
      whatsappPhoneId: "ID técnico",
      whatsappFlowInbound: "1. O cliente escreve para o WhatsApp conectado.",
      whatsappFlowInbox: "2. A Novua cria a conversa e prioriza por valor.",
      whatsappFlowReply: "3. A equipe responde pelo Inbox e o cliente recebe no celular.",
      whatsappNextConnected: "Próximo passo: envie uma mensagem de teste de outro celular e responda pelo Inbox.",
      whatsappNextDisconnected: "Próximo passo: clique em Conectar com Meta e autorize o número do cliente.",
      dangerTitle: "Zona perigosa",
      dangerHelp: "Remove o workspace, canal configurado e todos os dados associados.",
      dangerWarning:
        "Esta ação é irreversível. Serão removidos contatos, conversas, mensagens e acessos.",
      dangerConfirmationLabel: "Digite o nome do workspace para confirmar",
      dangerDeleteLabel: "Excluir workspace e dados",
      dangerDeletingLabel: "Excluindo...",
      dangerDeletedLabel: "Excluindo workspace. Redirecionando...",
      dangerError: "Não foi possível excluir o workspace.",
    };
  }

  return {
    channelsEmpty: "WhatsApp is configured with Novua during onboarding.",
    channelUsage: "It is used to receive and reply to inbound messages.",
    channelsNote: "Configured by Novua during onboarding.",
    requestSetup: "Request setup",
    requestWhatsAppSetup: "Request WhatsApp setup",
    requestInstagramSetup: "Request Instagram setup",
    updateWhatsAppSetup: "Update request",
    updateInstagramSetup: "Update Instagram request",
    setupRequested: "Setup requested",
    setupInProgress: "Setup in progress",
    setupRequestedNote: "We are preparing the real WhatsApp connection with you.",
    setupInstagramRequestedNote: "We are preparing the real Instagram connection with your Meta Business.",
    setupPhoneRequired: "WhatsApp phone is required.",
    setupInstagramRequired: "Instagram handle is required.",
    setupNumberLabel: "WhatsApp number",
    setupNumberPlaceholder: "+1 415 555 0101",
    setupInstagramHandleLabel: "Instagram handle",
    setupInstagramHandlePlaceholder: "@clinic",
    instagramHandle: "Connected handle",
    instagramChannelHelp:
      "Connect the client's Instagram Business account through their Meta. Novua activates the channel once authorization is ready.",
    setupMetaVerifiedLabel: "Is Meta Business verified?",
    setupMetaVerifiedYes: "Yes",
    setupMetaVerifiedNo: "No",
    setupNotesLabel: "Note",
    setupNotesPlaceholder: "Contact name, availability or any useful detail.",
    inviteTitle: "Add agents or admins to this workspace.",
    inviteEmail: "Email",
    inviteRole: "Role",
    inviteUser: "Invite user",
    invitePending: "Sending invite...",
    inviteSuccess: "Invite sent.",
    inviteAdmin: "Admin",
    inviteAgent: "Agent",
    inviteOwner: "Owner",
    inviteError: "Could not send invite.",
    seatLimitError: "Seat limit reached for this plan.",
    pendingInvites: "Pending invites",
    resendInvite: "Resend",
    cancelInvite: "Cancel",
    resendPending: "Resending...",
    cancelPending: "Cancelling...",
    inviteResent: "Invite resent.",
    inviteCancelled: "Invite cancelled.",
    removeUser: "Remove access",
    removingUser: "Removing...",
    removeUserSuccess: "Access removed.",
    removeUserError: "Could not remove access.",
    reassignPlaceholder: "Reassign to...",
    reassignAction: "Reassign",
    reassigningAction: "Reassigning...",
    reassignSuccess: "Open conversations reassigned.",
    reassignError: "Conversations could not be reassigned.",
    businessSetupTitle: "How value is calculated",
    businessSetupHelp:
      "Define how much each type of conversation is worth. This determines what appears first in the inbox.",
    businessSetupName: "Business name",
    businessSetupLeadTypesBlock: "Lead types and estimated value (€)",
    businessSetupLeadTypes: "What types of inquiries do you receive?",
    businessSetupAddLeadType: "+ Add type",
    businessSetupLeadTypeName: "Name",
    businessSetupEstimatedValue: "Estimated value (€)",
    businessSetupRemoveLeadType: "Remove",
    businessSetupSave: "Save configuration",
    businessSetupSaving: "Saving...",
    businessSetupBackfill: "Recalculate conversations",
    businessSetupBackfilling: "Recalculating...",
    businessSetupBackfillSuccess: "Conversations updated",
    businessSetupReseedDemo: "Reseed demo",
    businessSetupReseedingDemo: "Reseeding demo...",
    businessSetupReseedDemoSuccess: "Demo recreated.",
    businessSetupReseedDemoConfirm:
      "This will delete the current demo leads for this account and recreate the base demo. Continue?",
    businessSetupSuccess: "Configuration saved.",
    businessSetupError: "Could not save configuration.",
    pilotFeedbackTitle: "Report issue",
    pilotFeedbackHelp: "",
    pilotFeedbackCategory: "Category",
    pilotFeedbackMessage: "Tell us what happened or what should improve.",
    pilotFeedbackSubmit: "Send feedback",
    pilotFeedbackSubmitting: "Sending...",
    pilotFeedbackSuccess: "Feedback sent.",
    pilotFeedbackError: "Could not send feedback.",
    pilotFeedbackBug: "Bug",
    pilotFeedbackGeneral: "Feedback",
    pilotFeedbackFeature: "Feature request",
    pilotFeedbackHistoryTitle: "Your reports",
    pilotFeedbackHistoryEmpty: "You have not sent reports yet.",
    pilotFeedbackHistoryStatus: "Status",
    pilotFeedbackHistoryPage: "Page",
    pilotFeedbackHistoryReply: "Novua reply",
    pilotFeedbackStatusNew: "New",
    pilotFeedbackStatusReviewed: "Reviewed",
    pilotFeedbackStatusClosed: "Closed",
    accountTitle: "Your access",
    accountHelp: "Account information for the user you're logged in with.",
    accountRole: "Role",
    accountWorkspace: "Workspace",
    accountEmail: "Email",
    accountPermissions: "Permissions",
    accountPermissionsAgent: "You can manage conversations, reply to messages, and report issues.",
    accountPermissionsAdmin: "You can configure the workspace, manage the team, and operate conversations.",
    systemAiAssistance: "AI assistance",
    systemFollowUpAutomation: "Automated follow-up",
    systemWhatsappWebhook: "WhatsApp webhook",
    noTeamMembers: "No team members yet.",
    settingsUnavailable: "Settings requires an authenticated, configured workspace.",
    workspaceModeTitle: "Workspace mode",
    workspaceModeInternal: "Internal demo workspace. Internal tools visible.",
    workspaceModeCustomerDemo: "Customer demo workspace. Setup visible, internal tools hidden.",
    workspaceModeCustomer: "Customer workspace. Setup and feedback available.",
    requestError: "Could not request setup.",
    embeddedConnectTitle: "Connect with Meta",
    embeddedConnectHelp:
      "Log in with Meta and authorize your number once. If it was already connected, use this only when messages stop arriving.",
    embeddedConnectAction: "Connect with Meta",
    embeddedReconnectAction: "Reconnect channel",
    embeddedSdkLoading: "Loading connection...",
    embeddedSdkPreparing: "Preparing Meta...",
    embeddedConnectSuccess: "WhatsApp connected through Meta.",
    embeddedConnectError: "Could not open the Meta connection flow.",
    embeddedSaveError: "Meta finished the flow, but Novua could not save the connection.",
    embeddedFallbackTitle: "If Meta does not let you finish",
    embeddedFallbackHelp: "Try again from this button. If Meta keeps blocking the flow, contact Novua.",
    whatsappHowTitle: "How it works",
    whatsappHowConnected:
      "This number already receives messages in Novua. Every inbound WhatsApp creates or updates a conversation in Inbox.",
    whatsappHowDisconnected:
      "Connect the number through Meta so messages enter Inbox automatically.",
    whatsappNumber: "Connected number",
    whatsappPhoneId: "Technical ID",
    whatsappFlowInbound: "1. The customer writes to the connected WhatsApp number.",
    whatsappFlowInbox: "2. Novua creates the conversation and prioritizes it by value.",
    whatsappFlowReply: "3. The team replies from Inbox and the customer receives it on their phone.",
    whatsappNextConnected: "Next step: send a test message from another phone and reply from Inbox.",
    whatsappNextDisconnected: "Next step: click Connect with Meta and authorize the customer's number.",
    dangerTitle: "Danger zone",
    dangerHelp: "Delete the workspace, configured channel, and all associated data.",
    dangerWarning: "This action is irreversible. Contacts, conversations, messages, and team access will be deleted.",
    dangerConfirmationLabel: "Type the workspace name to confirm",
    dangerDeleteLabel: "Delete workspace and data",
    dangerDeletingLabel: "Deleting...",
    dangerDeletedLabel: "Deleting workspace. Redirecting...",
    dangerError: "Could not delete the workspace.",
  };
}

export function formatRoleLabel(lang: string, role: string) {
  if (lang === "pt") {
    if (role === "owner") return "Proprietário";
    if (role === "admin") return "Admin";
    return "Agente";
  }

  if (lang === "en") {
    if (role === "owner") return "Owner";
    if (role === "admin") return "Admin";
    return "Agent";
  }

  if (role === "owner") return "Propietario";
  if (role === "admin") return "Admin";
  return "Agente";
}
